apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-jaeger-go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-jaeger-go-service
  template:
    metadata:
      labels:
        app: kubernetes-jaeger-go-service
    spec:
      containers:
        - name: kubernetes-jaeger-go-service
          image: kubernetes-jaeger-go-service
          ports:
            - containerPort: 8080